spring.application.name=Animeverse_JAVA
spring.config.import=optional:file:env.properties
server.port=3001
spring.datasource.url=jdbc:postgresql://localhost:5432/AnimeVerse
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# JWT / Cloudinary placeholders
jwt.secret=y8P0qvG5zU9n3QmR2sV1h4Kj7LxB6tYwZc0F2u9N1bM
cloudinary.cloud_name=Root
cloudinary.api_key=974358591478654
cloudinary.api_secret=iiNnFQmITBZHQM_wgdU1KNRxFTM

# trending interval in ms (default 1 hour)
trending.fetch.interval=3600000
