spring.application.name=Animeverse_JAVA
spring.config.import=optional:file:env.properties
server.port=3001
spring.datasource.url=jdbc:postgresql://localhost:5432/AnimeVerse
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# JWT / Cloudinary placeholders
jwt.secret=5A7D9F2B4E8C1A3D6F0B9E2C5A8D3F1E7B4A2D9C6E8F0A3B5C7D9E1F4A6C8B3
cloudinary.cloud_name=Root
cloudinary.api_key=974358591478654
cloudinary.api_secret=iiNnFQmITBZHQM_wgdU1KNRxFTM

# trending interval in ms (default 1 hour)
trending.fetch.interval=3600000
